### ISSUE TITLE
perihal ekstraksi GLCM

### ISSUE THREAD

**Issue by AgnesNovita** [RidhoIlahi07/Pengolah-Citra-Digital#1]
hallo bg, saya ingin menanyakan tentang codingan ini, untuk ekstraksi GLCMnya.. untuk ekstraksinya bagian sudut 0-135 dan rumus untuk contras homogeneity entropy dan energy dapat dari mana ya bg? soalnya dari saya sedikit berbeda rumusnya bg begitu.. Termakasih bang

**Comment by RidhoIlahi07** [comment]
Halo selamat malam
Sebelumnya saya lupa ini siapa
Agar lebih enak kontak saya di nomer telepon

Hormat saya
RIDHO ILAHI

CP :
082359027400
